load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "StringSchemaTest",
  srcs = ["StringSchemaTest.java"],
  test_class = "slash.schemas.StringSchemaTest",
  deps = [
    "//schemas",
    "//third_party:junit4",
    "//third_party:truth"
  ]
)
