load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "PropertyMapTest",
  srcs = ["PropertyMapTest.java"],
  test_class = "slash.data.PropertyMapTest",
  deps = [
    "//data",
    "//third_party:junit4",
    "//third_party:truth"
  ]
)
